apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointments-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      tier: appointments
      app: dice
  template:
    metadata:
      labels:
        tier: appointments
        app: dice
    spec:
      containers:
      - name: appointments
        image: maryammoeed1/appointment-service:latest
        ports:
        - containerPort: 7070
          name: tcp
        resources:
          limits:
            memory: "256Mi"
            cpu: "200m"
          requests:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /health
            port: 7070
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 7070
          initialDelaySeconds: 5
          periodSeconds: 3

---
apiVersion: v1
kind: Service
metadata:
  name: appointments
spec:
  selector:
    tier: appointments
    app: dice
  ports:
  - protocol: TCP
    port: 7070
    targetPort: 7070
