apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      tier: frontend
      app: dice
  template:
    metadata:
      labels:
        tier: frontend
        app: dice
    spec:
      containers:
      - name: frontend
        image: maryammoeed1/frontend-service:latest
        env:
        - name: APPOINTMENTS_URL
          value: appointments:7070
        - name: DOCTORS_URL
          value: doctors:9090
        ports:
        - containerPort: 3000
          name: tcp
        resources:
          limits:
            memory: "256Mi"
            cpu: "200m"
          requests:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 3

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    tier: frontend
    app: dice
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 31000
  type: NodePort
