apiVersion: apps/v1
kind: Deployment
metadata:
  name: doctors-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      tier: doctors
      app: dice
  template:
    metadata:
      labels:
        tier: doctors
        app: dice
    spec:
      containers:
      - name: doctors
        image: maryammoeed1/doctor-service:latest
        ports:
        - containerPort: 9090
          name: tcp
        resources:
          limits:
            memory: "256Mi"
            cpu: "200m"
          requests:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /health
            port: 9090
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 9090
          initialDelaySeconds: 5
          periodSeconds: 3

---
apiVersion: v1
kind: Service
metadata:
  name: doctors
spec:
  selector:
    tier: doctors
    app: dice
  ports:
  - protocol: TCP
    port: 9090
    targetPort: 9090
