name: CICD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  build-and-push-doctors:
    runs-on: ubuntu-latest
    if: "contains(github.event_path, 'doctors/')"
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push Docker image for Doctors
      env:
        VERSION: ${{ github.sha }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker buildx create --use
        docker buildx inspect --bootstrap
        docker buildx build --platform linux/amd64,linux/arm64 -t maryammoeed1/doctors-service:${VERSION} ./doctors --push

  build-and-push-appointments:
    runs-on: ubuntu-latest
    if: "contains(github.event_path, 'appointments/')"
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push Docker image for Appointments
      env:
        VERSION: ${{ github.sha }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker buildx create --use
        docker buildx inspect --bootstrap
        docker buildx build --platform linux/amd64,linux/arm64 -t maryammoeed1/appointments-service:${VERSION} ./appointments --push

  build-and-push-frontend:
    runs-on: ubuntu-latest
    if: "contains(github.event_path, 'frontend/')"
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push Docker image for Frontend
      env:
        VERSION: ${{ github.sha }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker buildx create --use
        docker buildx inspect --bootstrap
        docker buildx build --platform linux/amd64,linux/arm64 -t maryammoeed1/frontends-service:${VERSION} ./frontend --push

  update-compose:
    runs-on: ubuntu-latest
    needs: [build-and-push-doctors, build-and-push-appointments, build-and-push-frontend]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Update Docker Compose
      run: |
        sed -i 's#maryammoeed1/doctors-service:.*#maryammoeed1/doctors-service:${{ github.event.workflow_run.build-and-push-doctors.conclusion == 'success' }}#' docker-compose.yaml
        sed -i 's#maryammoeed1/appointments-service:.*#maryammoeed1/appointments-service:${{ github.event.workflow_run.build-and-push-appointments.conclusion == 'success' }}#' docker-compose.yaml
        sed -i 's#maryammoeed1/frontends-service:.*#maryammoeed1/frontends-service:${{ github.event.workflow_run.build-and-push-frontend.conclusion == 'success' }}#' docker-compose.yaml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
