name: CICD

on:
  push:
    branches: [ main ]
    paths:
      - 'doctors/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'doctors/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./doctors
        file: ./doctors/Dockerfile
        push: true
        tags: maryammoeed1/doctors-service:${{ github.sha }}
