name: Frontend CICD

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'frontend/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./frontend
        file: ./frontend/Dockerfile
        push: true
        tags: maryammoeed1/frontend-service:${{ github.sha }}

    - name: Update docker-compose.yml
      run: |
        sed -i 's/maryammoeed1\/frontend-service:.*/maryammoeed1\/frontend-service:${{ github.sha }}/' docker-compose.yml
      working-directory: ${{ github.workspace }}

    - name: Check for changes
      id: git-check
      run: |
        git diff
        if git diff --quiet; then
          echo "::set-output name=changes::false"
        else
          echo "::set-output name=changes::true"
        fi

    - name: Commit and push if changed
      if: steps.git-check.outputs.changes == 'true'
      run: |
        git config --global user.email "maryammoeed68@gmail.com"
        git config --global user.name "maryammoeed"
        git add docker-compose.yml
        git commit -m "Update docker-compose.yml for frontend"
        git push
